import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import { Jost } from 'next/font/google';

// Настраиваем шрифт Jost
const jost = Jost({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-jost',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={jost.variable}
      >
        {children}
      </body>
    </html>
  );
}
